### ISSUE TITLE
Desktop Streamer Can't Start Music

### ISSUE THREAD

**Issue by azel1** [Vinyzu/MjolnirAiO#7]
Exception in thread Thread-5 (streamer):
Traceback (most recent call last):
  File "C:\Users\azel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-9 (threaded_streamer):
    Traceback (most recent call last):
self.run()  File "C:\Users\azel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner

  File "C:\Users\azel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
        self.run()
  File "C:\Users\azel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
  File "C:\Users\azel\Desktop\MjolnirAiO-main\mjolnir.py", line 761, in streamer
self._target(*self._args, **self._kwargs)    self.threaded_streamer(combo[i], ports[i], self.like, self.max)

  File "C:\Users\azel\Desktop\MjolnirAiO-main\mjolnir.py", line 835, in threaded_streamer
  File "C:\Users\azel\Desktop\MjolnirAiO-main\mjolnir.py", line 835, in threaded_streamer
        testx = int(requests.get(url).text.split(" songs")[0].split()[-1])
testx = int(requests.get(url).text.split(" songs")[0].split()[-1])ValueError
: invalid literal for int() with base 10: 'src="https://open.spotifycdn.com/cdn/build/mobile-web-player/vendor~mobile-web-player.285bf896.js"></script></body></html>'ValueError
: invalid literal for int() with base 10: 'src="https://open.spotifycdn.com/cdn/build/mobile-web-player/vendor~mobile-web-player.285bf896.js"></script></body></html>'

**Comment by YAGNIKHARIYANI** [comment]
is your problem solved i have this problem suggest me plz

**Comment by Vinyzu** [comment]
> is your problem solved i have this problem suggest me plz
> 
> 

Its bad code from my old days and its probably caused by regional differences

**Comment by YAGNIKHARIYANI** [comment]
BRO CAN YOU FIX FOR US PLEASE
